(defsystem "recurya"
  :class :package-inferred-system
  :version "0.1.0"
  :author "Satoshi Imai"
  :license "MIT"
  :pathname "./"
  :depends-on ("mito"
               "local-time"
               "alexandria"
               "log4cl"
               "com.inuoe.jzon"
               "uuid"
               ;; Web framework
               "ningle"
               "clack"
               "clack-handler-hunchentoot"
               "lack"
               "spinneret"
               "ironclad"
               "babel"
               "hunchentoot"
               "cl-ppcre"
               "dexador"
               ;; WardLisp language (external library)
               "wardlisp"
               ;; Markdown + HTML sanitizer for user-authored notebooks
               "3bmd"
               "plump"
               ;; Game logic
               "recurya/game/puzzle"
               "recurya/game/puzzles/adjacent"
               "recurya/game/puzzles/contains"
               "recurya/game/puzzles/nearest-point"
               "recurya/game/puzzles/safe-moves"
               "recurya/game/puzzles/choose-action"
               "recurya/game/puzzles/sqrt2-newton"
               "recurya/game/puzzles/registry"
               ;; Notebook
               "recurya/game/notebook"
               "recurya/game/notebook-parser"
               "recurya/game/notebooks/sicp-1-1-1"
               "recurya/game/notebooks/sicp-1-1-2"
               "recurya/game/notebooks/sicp-1-1-3"
               "recurya/game/notebooks/sicp-1-1-4"
               "recurya/game/notebooks/sicp-1-1-5"
               "recurya/game/notebooks/sicp-1-1-6"
               "recurya/game/notebooks/sicp-1-1-7"
               "recurya/game/notebooks/sicp-1-1-8"
               "recurya/game/notebooks/sicp-1-2-1"
               "recurya/game/notebooks/sicp-1-2-2"
               "recurya/game/notebooks/sicp-1-2-3"
               "recurya/game/notebooks/sicp-1-2-4"
               "recurya/game/notebooks/sicp-1-2-5"
               "recurya/game/notebooks/sicp-1-2-6"
               "recurya/game/notebooks/sicp-1-3-1"
               "recurya/game/notebooks/sicp-1-3-2"
               "recurya/game/notebooks/sicp-1-3-3"
               "recurya/game/notebooks/sicp-1-3-4"
               "recurya/game/notebooks/sicp-2-1-1"
               "recurya/game/notebooks/sicp-2-1-2"
               "recurya/game/notebooks/sicp-2-1-3"
               "recurya/game/notebooks/sicp-2-1-4"
               "recurya/game/notebooks/sicp-2-2-1"
               "recurya/game/notebooks/sicp-2-2-2"
               "recurya/game/notebooks/sicp-2-2-3"
               "recurya/game/notebooks/sicp-2-2-4"
               "recurya/game/notebooks/sicp-2-3-1"
               "recurya/game/notebooks/sicp-2-3-2"
               "recurya/game/notebooks/sicp-2-3-3"
               "recurya/game/notebooks/sicp-2-3-4"
               "recurya/game/notebooks/sicp-2-4-1"
               "recurya/game/notebooks/sicp-2-4-2"
               "recurya/game/notebooks/sicp-2-4-3"
               "recurya/game/notebooks/sicp-2-5-1"
               "recurya/game/notebooks/sicp-2-5-2"
               "recurya/game/notebooks/sicp-2-5-3"
               "recurya/game/notebooks/sicp-3-1-1"
               "recurya/game/notebooks/sicp-3-1-2"
               "recurya/game/notebooks/sicp-3-1-3"
               "recurya/game/notebooks/sicp-3-2-1"
               "recurya/game/notebooks/sicp-3-2-2"
               "recurya/game/notebooks/sicp-3-2-3"
               "recurya/game/notebooks/sicp-3-2-4"
               "recurya/game/notebooks/sicp-3-3-1"
               "recurya/game/notebooks/sicp-3-3-2"
               "recurya/game/notebooks/sicp-3-3-3"
               "recurya/game/notebooks/sicp-3-3-4"
               "recurya/game/notebooks/sicp-3-3-5"
               "recurya/game/notebooks/sicp-3-4-1"
               "recurya/game/notebooks/sicp-3-4-2"
               "recurya/game/notebooks/sicp-3-5-1"
               "recurya/game/notebooks/sicp-3-5-2"
               "recurya/game/notebooks/sicp-3-5-3"
               "recurya/game/notebooks/sicp-3-5-4"
               "recurya/game/notebooks/sicp-3-5-5"
               "recurya/game/notebooks/registry"
               ;; Arena
               "recurya/game/arena"
               "recurya/game/scenario"
               ;; Shared utilities
               "recurya/utils/common"
               "recurya/utils/html-sanitize"
               ;; Database layer
               "recurya/db/core"
               "recurya/db/jsonb"
               "recurya/db/users"
               "recurya/db/posts"
               "recurya/db/user-notebooks"
               "recurya/db/learn"
               "recurya/db"
               ;; Models
               "recurya/models/users"
               "recurya/models/post"
               "recurya/models/user-notebook"
               "recurya/models/learn-progress"
               "recurya/models/learn-cell-code"
               "recurya/models/learn-submission"
               ;; Web layer
               "recurya/web/app"
               "recurya/web/auth"
               "recurya/web/ui/styles"
               "recurya/web/ui/layout"
               "recurya/web/ui/login"
               "recurya/web/ui/errors"
               "recurya/web/ui/account"
               ;; Blog UI
               "recurya/web/ui/posts"
               "recurya/web/ui/post-form"
               "recurya/web/ui/user-notebook-form"
               "recurya/web/ui/user-notebooks"
               "recurya/web/ui/blog"
               "recurya/web/ui/blog-post"
               "recurya/web/routes"
               ;; WardLisp UI
               "recurya/web/ui/wardlisp-home"
               "recurya/web/ui/learn-home"
               "recurya/web/ui/notebook"
               "recurya/web/ui/editor"
               "recurya/web/ui/puzzle"
               "recurya/web/ui/arena"
               "recurya/web/ui/playground"
               "recurya/web/ui/reference"
               "recurya/web/routes-wardlisp"
               "recurya/web/server")
  :description "Recurya - Lisp learning game web system"
  :in-order-to ((test-op (test-op "recurya/tests"))))

(defsystem "recurya/tests"
  :class :package-inferred-system
  :pathname "tests/"
  :depends-on ("recurya"
               "rove"
               "clack-test"
               ;; Test support modules
               "recurya/tests/support/db"
               ;; Utils tests
               "recurya/tests/utils/common"
               "recurya/tests/utils/html-sanitize"
               ;; DB tests
               "recurya/tests/db/core"
               "recurya/tests/db/jsonb"
               "recurya/tests/db/users"
               "recurya/tests/db/posts"
               "recurya/tests/db/user-notebooks"
               "recurya/tests/db/learn"
               ;; Web tests
               "recurya/tests/web/oauth"
               "recurya/tests/web/routes"
               "recurya/tests/web/learn-routes"
               ;; Game tests
               "recurya/tests/game/puzzle"
               "recurya/tests/game/arena"
               "recurya/tests/game/notebook"
               "recurya/tests/game/notebook-parser"
               "recurya/tests/game/notebooks/sicp-1-1-1"
               "recurya/tests/game/notebooks/sicp-1-1-2"
               "recurya/tests/game/notebooks/sicp-1-1-3"
               "recurya/tests/game/notebooks/sicp-1-1-4"
               "recurya/tests/game/notebooks/sicp-1-1-5"
               "recurya/tests/game/notebooks/sicp-1-1-6"
               "recurya/tests/game/notebooks/sicp-1-1-7"
               "recurya/tests/game/notebooks/sicp-1-1-8"
               "recurya/tests/game/notebooks/sicp-1-2-1"
               "recurya/tests/game/notebooks/sicp-1-2-2"
               "recurya/tests/game/notebooks/sicp-1-2-3"
               "recurya/tests/game/notebooks/sicp-1-2-4"
               "recurya/tests/game/notebooks/sicp-1-2-5"
               "recurya/tests/game/notebooks/sicp-1-2-6"
               "recurya/tests/game/notebooks/sicp-1-3-1"
               "recurya/tests/game/notebooks/sicp-1-3-2"
               "recurya/tests/game/notebooks/sicp-1-3-3"
               "recurya/tests/game/notebooks/sicp-1-3-4"
               "recurya/tests/game/notebooks/sicp-2-1-1"
               "recurya/tests/game/notebooks/sicp-2-1-2"
               "recurya/tests/game/notebooks/sicp-2-1-3"
               "recurya/tests/game/notebooks/sicp-2-1-4"
               "recurya/tests/game/notebooks/sicp-2-2-1"
               "recurya/tests/game/notebooks/sicp-2-2-2"
               "recurya/tests/game/notebooks/sicp-2-2-3"
               "recurya/tests/game/notebooks/sicp-2-2-4"
               "recurya/tests/game/notebooks/sicp-2-3-1"
               "recurya/tests/game/notebooks/sicp-2-3-2"
               "recurya/tests/game/notebooks/sicp-2-3-3"
               "recurya/tests/game/notebooks/sicp-2-3-4"
               "recurya/tests/game/notebooks/sicp-2-4-1"
               "recurya/tests/game/notebooks/sicp-2-4-2"
               "recurya/tests/game/notebooks/sicp-2-4-3"
               "recurya/tests/game/notebooks/sicp-2-5-1"
               "recurya/tests/game/notebooks/sicp-2-5-2"
               "recurya/tests/game/notebooks/sicp-2-5-3"
               "recurya/tests/game/notebooks/sicp-3-1-1"
               "recurya/tests/game/notebooks/sicp-3-1-2"
               "recurya/tests/game/notebooks/sicp-3-1-3"
               "recurya/tests/game/notebooks/sicp-3-2-1"
               "recurya/tests/game/notebooks/sicp-3-2-2"
               "recurya/tests/game/notebooks/sicp-3-2-3"
               "recurya/tests/game/notebooks/sicp-3-2-4"
               "recurya/tests/game/notebooks/sicp-3-3-1"
               "recurya/tests/game/notebooks/sicp-3-3-2"
               "recurya/tests/game/notebooks/sicp-3-3-3"
               "recurya/tests/game/notebooks/sicp-3-3-4"
               "recurya/tests/game/notebooks/sicp-3-3-5"
               "recurya/tests/game/notebooks/sicp-3-4-1"
               "recurya/tests/game/notebooks/sicp-3-4-2"
               "recurya/tests/game/notebooks/sicp-3-5-1"
               "recurya/tests/game/notebooks/sicp-3-5-2"
               "recurya/tests/game/notebooks/sicp-3-5-3"
               "recurya/tests/game/notebooks/sicp-3-5-4"
               "recurya/tests/game/notebooks/sicp-3-5-5"
               ;; WardLisp integration tests
               "recurya/tests/wardlisp-integration"
               ;; Main test runner
               "recurya/tests/all")
  :perform (test-op (o c)
             (unless (symbol-call :recurya/tests/all :run-all-tests)
               (error "Some tests failed"))))
