;;;; scripts/inject-sicp-solutions.lisp --- Inject canonical SICP solutions
;;;; into the markdown fixtures generated by sicp-to-markdown.lisp.
;;;;
;;;; Usage:
;;;;   (load "scripts/sicp-to-markdown.lisp")
;;;;   (load "scripts/inject-sicp-solutions.lisp")
;;;;   (scripts/inject-sicp-solutions:inject-all-sicp-solutions!)
;;;;
;;;; Pipeline:
;;;;   1. For every notebook NB under recurya/game/notebooks/registry,
;;;;      open the matching `tests/game/notebooks/sicp-X-Y-Z.lisp' and
;;;;      walk its top-level forms looking for DEFTEST forms.
;;;;   2. Inside each DEFTEST, find the (POSITION :EX-* CELLS :KEY #'CELL-ID)
;;;;      call to learn which exercise cell the test targets, and the
;;;;      `(COND ((= I EX-IDX) "<CODE>") ...)' arm that supplies the
;;;;      canonical code.  Records the (cell-id, code) pair.
;;;;   3. Look up the matching exercise cell on the notebook to get the
;;;;      flattened description (the same flattening
;;;;      sicp-to-markdown:flatten-description applies).
;;;;   4. Open `docs/sicp/<id>.md' and, immediately after the
;;;;      corresponding `===exercise: <desc>===' block (and any
;;;;      `===expect===' blocks that belong to it), insert a
;;;;      `===solution: <desc>===' cell with the canonical code.
;;;;
;;;; If a test cannot be matched (unknown form layout, missing exercise
;;;; cell, etc.), the unresolved entry is appended to a TODO file at
;;;; `docs/sicp-solution-todos.md' so a human can paste solutions in
;;;; later.

(defpackage #:scripts/inject-sicp-solutions
  (:use #:cl)
  (:import-from #:recurya/game/notebook
                #:notebook-id
                #:notebook-cells
                #:cell-id
                #:cell-kind
                #:cell-description)
  (:import-from #:recurya/game/notebooks/registry
                #:all-notebooks)
  (:import-from #:scripts/sicp-to-markdown
                #:flatten-description)
  (:export #:inject-all-sicp-solutions!
           #:extract-canonical-solutions))

(in-package #:scripts/inject-sicp-solutions)

;;; ---------------------------------------------------------------------------
;;; Reading a test file with the standard CL reader
;;; ---------------------------------------------------------------------------

(defun read-all-forms (path)
  "Return all top-level forms in PATH as a list. Uses the CL reader and
   tolerates package designators that may not exist in the host image
   by interning bare symbols into a throwaway package. The notebook
   test files contain only standard reader macros (#: package prefix
   on defpackage names) and quoted literals, so plain CL:READ works."
  (with-open-file (s path :direction :input)
    (loop with eof = (gensym "EOF")
          for form = (handler-case (read s nil eof)
                       (error (e)
                         (warn "Skipping unreadable form in ~A: ~A" path e)
                         eof))
          until (eq form eof)
          collect form)))

(defun walk (form on-cons)
  "Pre-order walk over FORM, calling ON-CONS on every cons cell."
  (when (consp form)
    (funcall on-cons form)
    (dolist (child form)
      (walk child on-cons))))

;;; ---------------------------------------------------------------------------
;;; Extracting (cell-id . code-string) pairs from a deftest body
;;; ---------------------------------------------------------------------------

(defun keyword-from-cell-id-form (form)
  "If FORM looks like `(POSITION :EX-FOO CELLS ... :KEY #'CELL-ID)' (or
   uses package-qualified `cell-id'), return the keyword :EX-FOO.
   Returns NIL otherwise."
  (when (and (consp form)
             (let ((head (car form)))
               (or (eq head 'position)
                   (and (symbolp head)
                        (string= (symbol-name head) "POSITION")))))
    (let ((second (and (cdr form) (cadr form))))
      (when (keywordp second) second))))

(defun expand-format-tilde (fmt-string args-by-symbol)
  "Expand a tiny subset of FORMAT directives in FMT-STRING:
     ~A   replaced with the next ARG (looked up by symbol name in
          ARGS-BY-SYMBOL: a hash mapping uppercase symbol-name strings
          to source strings)
     ~%   replaced with #\\Newline
   Other directives cause the function to return NIL (caller falls back
   to the TODO list).  ARGS-BY-SYMBOL is consulted for the next
   substitution; the matching argument is identified by ARGS, a list of
   symbols passed alongside the format string at the call site."
  ;; This helper takes ARGS-BY-SYMBOL pre-resolved into a list of strings.
  (let ((out (make-array 256 :element-type 'character
                              :fill-pointer 0
                              :adjustable t))
        (i 0)
        (n (length fmt-string))
        (args (copy-list args-by-symbol)))
    (loop while (< i n) do
      (let ((c (char fmt-string i)))
        (cond
          ((char= c #\~)
           (when (>= (1+ i) n)
             (return-from expand-format-tilde nil))
           (let ((d (char fmt-string (1+ i))))
             (case d
               ((#\A #\a)
                (unless args
                  (return-from expand-format-tilde nil))
                (let ((next (pop args)))
                  (loop for ch across next do (vector-push-extend ch out)))
                (incf i 2))
               (#\%
                (vector-push-extend #\Newline out)
                (incf i 2))
               (t (return-from expand-format-tilde nil)))))
          (t (vector-push-extend c out)
             (incf i)))))
    (when args
      ;; Unused arguments — pattern doesn't match expectations.
      (return-from expand-format-tilde nil))
    (coerce out 'simple-string)))

(defun string-form-from-cond-arm (arm prelude-table)
  "ARM looks like `((= I EX-IDX) ...)' — return the canonical code
   string in the body when one of the supported patterns matches:
     1. A single literal string in the body.
     2. A single FORMAT call of the form
          (format nil <LITERAL-STRING> SYMBOL...)
        where each SYMBOL is a defparameter whose value is recorded
        in PRELUDE-TABLE (hash: uppercase symbol-name -> string).
   Returns NIL when nothing matches."
  (when (and (consp arm) (consp (car arm)))
    (let* ((test (car arm))
           (head (and (consp test) (car test))))
      (when (and (symbolp head)
                 (string= (symbol-name head) "="))
        (let* ((body (cdr arm)))
          (cond
            ;; Direct literal string.
            ((and (= 1 (length body)) (stringp (first body)))
             (first body))
            ;; Bare symbol reference, e.g. *MY-SOLUTION*.
            ((and (= 1 (length body))
                  (symbolp (first body))
                  (gethash (symbol-name (first body)) prelude-table))
             (gethash (symbol-name (first body)) prelude-table))
            ;; (format nil "..." sym...)
            ((and (= 1 (length body))
                  (consp (first body))
                  (let ((h (car (first body))))
                    (and (symbolp h)
                         (string= (symbol-name h) "FORMAT"))))
             (let* ((call (first body))
                    (args (cdr call)))
               (when (and (>= (length args) 2)
                          (let ((dest (first args)))
                            (or (null dest)
                                (and (symbolp dest)
                                     (string= (symbol-name dest) "NIL"))))
                          (stringp (second args)))
                 (let ((fmt (second args))
                       (sym-args (cddr args)))
                   ;; Resolve each symbol argument from PRELUDE-TABLE.
                   (let ((resolved
                          (loop for sa in sym-args
                                for v = (and (symbolp sa)
                                             (gethash (symbol-name sa)
                                                      prelude-table))
                                when (not v) return :unresolved
                                collect v)))
                     (unless (eq resolved :unresolved)
                       (expand-format-tilde fmt resolved)))))))))))))

(defun extract-from-deftest (deftest-form prelude-table)
  "DEFTEST-FORM looks like (DEFTEST NAME ...). Return a list of
   (CELL-KEYWORD . CODE-STRING) pairs found in the form. May return
   NIL when the deftest is the structural smoke test (no canonical
   code) or when the layout doesn't match expectations."
  (let ((found-keyword nil)
        (found-strings 'nil))
    (walk deftest-form
          (lambda (cons)
            (let ((kw (keyword-from-cell-id-form cons)))
              (when kw (setf found-keyword kw)))
            ;; Collect cond arms that compare with a literal index var.
            (let ((str (string-form-from-cond-arm cons prelude-table)))
              (when str (push str found-strings)))))
    (cond
      ((and found-keyword
            (= 1 (length found-strings)))
       (list (cons found-keyword (first found-strings))))
      ((and found-keyword found-strings)
       ;; Multiple string arms — ambiguous, take none.
       'nil)
      (t 'nil))))

(defun build-prelude-table (forms)
  "Walk top-level FORMS and collect any
     (DEFPARAMETER NAME \"...\" [docstring])
   entries into a hash table keyed by uppercase symbol-name."
  (let ((tbl (make-hash-table :test 'equal)))
    (dolist (form forms)
      (when (and (consp form)
                 (symbolp (car form))
                 (string= (symbol-name (car form)) "DEFPARAMETER")
                 (>= (length form) 3)
                 (symbolp (second form))
                 (stringp (third form)))
        (setf (gethash (symbol-name (second form)) tbl) (third form))))
    tbl))

(defun extract-canonical-solutions (test-path)
  "Walk every DEFTEST in TEST-PATH and return an alist
   ((CELL-KEYWORD . CODE-STRING) ...). Duplicate keys (e.g. two
   different deftests targeting the same exercise) are kept as
   separate entries; the caller decides how to dedup."
  (let* ((forms (read-all-forms test-path))
         (prelude-table (build-prelude-table forms))
         (results 'nil))
    (dolist (form forms)
      (when (and (consp form)
                 (symbolp (car form))
                 (string= (symbol-name (car form)) "DEFTEST"))
        (dolist (pair (extract-from-deftest form prelude-table))
          (push pair results))))
    (nreverse results)))

;;; ---------------------------------------------------------------------------
;;; Mapping cell-id keyword -> exercise-cell description
;;; ---------------------------------------------------------------------------

(defun find-exercise-cell (nb cell-keyword)
  "Return the exercise cell on NB whose CELL-ID matches CELL-KEYWORD
   (compared by KEYWORDP equality first, then by string-equal on the
   symbol-name as a fallback for cells stored as plain strings)."
  (find-if (lambda (c)
             (and (eq (cell-kind c) :code-exercise)
                  (let ((cid (cell-id c)))
                    (cond
                      ((and (keywordp cid) (eq cid cell-keyword)) t)
                      ((and (stringp cid)
                            (string-equal
                             cid (symbol-name cell-keyword)))
                       t)))))
           (notebook-cells nb)))

;;; ---------------------------------------------------------------------------
;;; Markdown insertion
;;; ---------------------------------------------------------------------------

(defun string-trim-trailing-newlines (s)
  (let ((i (length s)))
    (loop while (and (plusp i)
                     (let ((c (char s (1- i))))
                       (or (char= c #\Newline) (char= c #\Return))))
          do (decf i))
    (subseq s 0 i)))

(defun fence-line-p (line)
  (and (>= (length line) 6)
       (string= line "===" :end1 3)
       (>= (length line) 6)
       (string= line "===" :start1 (- (length line) 3))))

(defun line-fence-kind+desc (line)
  "Return (values KIND DESC) for a fence line, where KIND is one of
   :PROSE :EVAL :EXERCISE :EXPECT :SOLUTION, or NIL if not recognized.
   DESC is the captured description string (after the colon) or NIL."
  (cond
    ((string= line "===prose===") (values :prose nil))
    ((string= line "===eval===") (values :eval nil))
    ((or (string= line "===expect===")
         (and (>= (length line) 13)
              (string= "===expect: " line :end2 11)
              (string= "===" line :start2 (- (length line) 3))))
     (values :expect
             (cond ((string= line "===expect===") nil)
                   (t (subseq line 11 (- (length line) 3))))))
    ((and (>= (length line) 16)
          (string= "===exercise: " line :end2 13)
          (string= "===" line :start2 (- (length line) 3)))
     (values :exercise (subseq line 13 (- (length line) 3))))
    ((and (>= (length line) 16)
          (string= "===solution: " line :end2 13)
          (string= "===" line :start2 (- (length line) 3)))
     (values :solution (subseq line 13 (- (length line) 3))))
    (t (values nil nil))))

(defun split-into-cell-blocks (md)
  "Split MD into a list of cell-block strings preserving order.
   Each block starts with a fence header line and contains all lines
   up to (but not including) the next fence header. Blank-line
   separators between blocks are dropped; the caller re-emits exactly
   one blank line between blocks during reassembly."
  (let* ((lines (cl-ppcre:split "(?<=\\n)" md))   ; keep newlines
         (blocks 'nil)
         (current 'nil))
    (flet ((push-block ()
             (when current
               (push (apply #'concatenate 'string (nreverse current))
                     blocks)
               (setf current 'nil))))
      (dolist (raw-line lines)
        (let ((line (string-right-trim '(#\Newline #\Return) raw-line)))
          (multiple-value-bind (kind desc)
              (line-fence-kind+desc line)
            (declare (ignore desc))
            (cond
              (kind
               (push-block)
               (push raw-line current))
              (t (when current (push raw-line current)))))))
      (push-block))
    (nreverse blocks)))

(defun block-fence-info (block)
  "Return (values KIND DESC) for the first line of BLOCK."
  (let* ((newline (position #\Newline block))
         (head (if newline (subseq block 0 newline) block)))
    (line-fence-kind+desc (string-right-trim '(#\Return) head))))

(defun build-solution-block (description code)
  "Return a string `===solution: <description>===\\n<code>' with no
   trailing newline."
  (format nil "===solution: ~A===~%~A"
          description
          (string-trim-trailing-newlines code)))

(defun blocks->md (blocks)
  "Reassemble BLOCKS into a single markdown string with exactly one
   blank line between each block. Preserves any trailing newlines on
   individual blocks but strips them before joining."
  (with-output-to-string (s)
    (loop for b in blocks
          for first-p = t then nil
          for trimmed = (string-trim-trailing-newlines b)
          do (unless first-p
               (write-char #\Newline s)
               (write-char #\Newline s))
          (write-string trimmed s))
    (write-char #\Newline s)))

(defun inject-solutions-into-blocks (blocks ex-desc->code)
  "BLOCKS is a list of cell-block strings, EX-DESC->CODE is a hash
   mapping flattened exercise descriptions to canonical code strings.
   Walk BLOCKS, and after the final ===expect=== that follows each
   ===exercise===, splice in a ===solution=== block.

   Returns (values NEW-BLOCKS INSERTED-DESCRIPTIONS)."
  (let ((out 'nil)
        (inserted 'nil)
        (i 0)
        (n (length blocks))
        (vec (coerce blocks 'simple-vector)))
    (loop while (< i n) do
      (let ((b (svref vec i)))
        (push b out)
        (multiple-value-bind (kind desc) (block-fence-info b)
          (cond
            ((eq kind :exercise)
             ;; Consume any following ===expect=== blocks first, then
             ;; emit the solution before moving on to the next cell.
             (incf i)
             (loop while (< i n)
                   for nb = (svref vec i)
                   while (eq (block-fence-info nb) :expect)
                   do (push nb out)
                   (incf i))
             (let ((code (gethash desc ex-desc->code)))
               (when code
                 (push (build-solution-block desc code) out)
                 (push desc inserted))))
            (t (incf i)))))
      finally (return (values (nreverse out) (nreverse inserted))))))

;;; ---------------------------------------------------------------------------
;;; Top-level driver
;;; ---------------------------------------------------------------------------

(defun project-relative (path)
  (merge-pathnames path (uiop:getcwd)))

(defun process-notebook (nb stats todos)
  "Process one notebook NB. Updates STATS plist (modified in place)
   and pushes TODO lines into TODOS as side effects."
  (let* ((nb-id (notebook-id nb))
         (slug (string-downcase (symbol-name nb-id)))
         (test-path (project-relative
                     (format nil "tests/game/notebooks/~A.lisp" slug)))
         (md-path (project-relative
                   (format nil "docs/sicp/~A.md" slug))))
    (unless (probe-file test-path)
      (push (format nil "- ~A: missing test file ~A"
                    slug (namestring test-path))
            (cdr todos))
      (return-from process-notebook))
    (unless (probe-file md-path)
      (push (format nil "- ~A: missing markdown file ~A"
                    slug (namestring md-path))
            (cdr todos))
      (return-from process-notebook))
    ;; Build descriptor map from canonical solutions.
    (let* ((extracted (extract-canonical-solutions test-path))
           (desc->code (make-hash-table :test 'equal)))
      (dolist (entry extracted)
        (let* ((cell-kw (car entry))
               (code (cdr entry))
               (cell (find-exercise-cell nb cell-kw)))
          (cond
            ((null cell)
             (push (format nil
                           "- ~A: extracted code for ~S but no matching ~
                            exercise cell on the notebook"
                           slug cell-kw)
                   (cdr todos)))
            (t
             (let ((desc (flatten-description (cell-description cell))))
               (setf (gethash desc desc->code) code))))))
      ;; Inject into the markdown.
      (let* ((md (alexandria:read-file-into-string md-path))
             (blocks (split-into-cell-blocks md)))
        (multiple-value-bind (new-blocks inserted)
            (inject-solutions-into-blocks blocks desc->code)
          (incf (getf (cdr stats) :files-touched))
          (incf (getf (cdr stats) :solutions-inserted) (length inserted))
          (when inserted
            (incf (getf (cdr stats) :files-modified)))
          (with-open-file (s md-path :direction :output
                                      :if-exists :supersede
                                      :if-does-not-exist :create)
            (write-string (blocks->md new-blocks) s))
          ;; Flag exercises that had no canonical code at all.
          (let ((cells-with-exercise
                 (remove-if-not (lambda (c)
                                  (eq (cell-kind c) :code-exercise))
                                (notebook-cells nb))))
            (dolist (cell cells-with-exercise)
              (let ((desc (flatten-description
                           (cell-description cell))))
                (unless (gethash desc desc->code)
                  (push (format nil
                                "- ~A: exercise has no canonical solution: ~A"
                                slug
                                (subseq desc 0
                                        (min 80 (length desc))))
                        (cdr todos)))))))))))

(defun inject-all-sicp-solutions! ()
  "Run the injection over every notebook in the registry. Returns a
   plist with statistics. Writes a TODO file at
   `docs/sicp-solution-todos.md' if any unresolved entries exist."
  (let ((stats (cons :stats (list :files-touched 0
                                  :files-modified 0
                                  :solutions-inserted 0)))
        (todos (cons :todos 'nil)))
    (dolist (nb (all-notebooks))
      (process-notebook nb stats todos))
    (let ((todo-path (project-relative "docs/sicp-solution-todos.md")))
      (cond
        ((cdr todos)
         (with-open-file (s todo-path :direction :output
                                      :if-exists :supersede
                                      :if-does-not-exist :create)
           (format s "# SICP solution injection: unresolved entries~%~%")
           (format s "Each entry is an exercise cell whose canonical ~
                      solution could not be located by ~
                      `inject-sicp-solutions.lisp`. Paste a solution ~
                      into the corresponding markdown file by hand.~%~%")
           (dolist (line (nreverse (cdr todos)))
             (format s "~A~%" line))))
        (t
         (when (probe-file todo-path)
           (delete-file todo-path)))))
    (cdr stats)))
